identifier_name:
  min_length: 1
  max_length: 50
  allowed_symbols: "_"

line_length:
  warning: 200
  error: 300
  ignores_comments: true
  ignores_urls: true

large_tuple:
  warning: 3
  error: 4

disabled_rules:
  - todo
  - for_where
  - file_length
  - force_cast
  - force_try
  - cyclomatic_complexity
  - generic_type_name
  - function_body_length
  - type_body_length

excluded:
  - Modules/Secrets/Sources/Secrets/SecretKey.swift
  - Modules/Account/Tests/AccountTests/Feedly/
  - Widget/Resources/Localized.swift
  - Shared/Extensions/NSAttributedString+NetNewsWire.swift


