identifier_name:
  min_length: 1
  max_length: 50

line_length:
  warning: 200
  error: 300
  ignores_comments: true
  ignores_urls: true

disabled_rules:
  - todo
  - for_where
  - file_length
  - force_cast

excluded:
  - Modules/Secrets/Sources/Secrets/SecretKey.swift
  - Modules/Account/Tests/AccountTests/Feedly/
  - Widget/Resources/Localized.swift

